### ISSUE TITLE
Output the json of strings used in the frontend with js

### ISSUE THREAD

**Issue by erikyo** [wp-blocks/make-pot#21]
Like this one:

https://developer.wordpress.org/cli/commands/i18n/make-json/

**Comment by plaksherie** [comment]
By the way, the script is incompatible with make-json, it makes the path "\assets\main-C13JnjQB.js:9", but you need "/assets/main-C13JnjQB.js:9" for md5 to work correctly

**Comment by erikyo** [comment]
This module not intended to be compatible with the wp-cli utility, and should fully cover also the make-json functionality in the future

Anyhow good to know about the reversed slashes, thanks, it seems that poedit (or even wordpress) works flawlessly with the any kind of slash while make-json seems not.

**Comment by erikyo** [comment]
@plaksherie the #23 was closed, thank you for the report
